### PR TITLE
add continuous integration workflows

### PR DESCRIPTION
**Pull request by danieleades**
Introduces a continuous integration workflow for the project

- build and test
- lint using clippy
- check that the docs build
- check the MSRV

is this of interest?

### CODE REVIEW

**Comment by danieleades** [comment]
@aryakaul i'm not sure all of the CI targets here make sense for your project, or that the current suite of tests would successfully verify them anyway (this is a copy and paste job). Thoughts?

**Comment by aryakaul** [comment]
Thanks again! I tried to set up something similar when I started the project but couldn't get it working so went with travis-ci. As I see it, the differences between this and what's currently up is the linting and checking of docs correct? Also, any reason you removed windows/macos targets? I expect RKM to work on macos, but maybe not windows.

**Comment by danieleades** [comment]
@aryakaul as you suspected, the mac-os job passes, but the windows does not (termion fails to compile).

**Comment by danieleades** [comment]
GitHub has failed to run some of the jobs, not sure why

**Comment by aryakaul** [comment]
Looking good! Just curious about the `docs` build test. What's it doing there? My understanding was docs are only necessary if one is writing a library crate instead of a binary crate?

**Comment by aryakaul** [comment]
Actually still appears to be failing. Error is:
```
Error when evaluating 'runs-on' for job 'test'. .github/workflows/CI.yml (Line: 11, Col: 14): Unexpected type of value '', expected type: OneOf.
```
Here's the relevant line: I looked for other examples on Github and this looks identical, so not sure what the problem is. 
https://github.com/aryakaul/rusty-krab-manager/blob/0f21fd6b581fa1ee7f21808fc48a1d31c9c658c0/.github/workflows/CI.yml#L11

**Comment by danieleades** [comment]
> Actually still appears to be failing. Error is:
> 
> ```
> Error when evaluating 'runs-on' for job 'test'. .github/workflows/CI.yml (Line: 11, Col: 14): Unexpected type of value '', expected type: OneOf.
> ```
> 
> Here's the relevant line: I looked for other examples on Github and this looks identical, so not sure what the problem is.
> 
> https://github.com/aryakaul/rusty-krab-manager/blob/0f21fd6b581fa1ee7f21808fc48a1d31c9c658c0/.github/workflows/CI.yml#L11

that's weird...
will take a look

**Pull request merged**
